### ISSUE TITLE
White lines in Kanban board

### ISSUE THREAD

**Issue by RakSrinaNa** [Reptarsrage/jira-carbon#19]
## What's the issue
In a Kanban board there's white lines in the header of the different columns.

## Steps to reproduce

By doing a Kanban I guess. I'm on a Jira version 8.8.1.

## Screenshots

This is repeated for every column
![image](https://user-images.githubusercontent.com/1688389/85984233-32dbb700-b9e9-11ea-9711-6861a3a8ec6e.png)

## Solutions

Replace the background value of `#ghx-column-header-group`.

As I saw this white part is applied from `<div id="ghx-column-header-group" class="ghx-column-header-group ghx-has-stats">` which defines `background: #fff` with the selector `#ghx-column-header-group`. Disabling this property do make the white stripes go away.

![image](https://user-images.githubusercontent.com/1688389/85984518-96fe7b00-b9e9-11ea-8f48-18889f803a9d.png)

## What version is affected by this problem
Jira 8.8.1

Though doesn't seem like Stylus shows me any infos about the stylesheet version, like if the headers are missing. Just updated it though so should be the last version.

**Comment by Rakambda** [comment]
I guess 76b604f8144d03c353bfec746dfd8e46db4a9daa fixed it
